### PR TITLE
Upgrade to Liquibase 3.10.1 (also liquibase-hibernate5)

### LINKED ISSUE #95: Excessive Index re-creation by Liquibase-Hibernate 3.6
See https://github.com/liquibase/liquibase-hibernate/issues/134

Affects e.g. UserRole if using spring-security-core plugin.

### PR DESCRIPTION
**Pull request by robertoschwald**
- This finally fixes the excessive index / foreign key constraint recreations
- Fixed tests by extracting changeLog part (Due to polluted outputCapture)
- Fixes GroovyChangeLogSpec if default JVM langauge is not en.
- String comparisons are now done without spaces in tests
- fixes #95 #100 #159

Tested successfully with Grails 4.0.3 in a fairly complex project.

### CODE REVIEW

**Comment by puneetbehl** [comment]
Thank you for the PR, can you please remove the extra spacing from the changes?

**Comment by robertoschwald** [comment]
I can. Isn't it better readable when indention is correct? With the PR it does not matter anymore, as spaces are removed before comparison anyway.

**Comment by davydotcom** [comment]
It probably would be easier not to change some of the indentations like the Specs where the quoted multiline strings have extra indentation. This affects the final string output.

**Comment by robertoschwald** [comment]
It doesn't matter as I've written, as all blanks are removed from the fixtures and the output before comparison to make the tests more robust, but I will change it back on your request.

**Comment by puneetbehl** [comment]
I am not very sure but I think there are issues while tracing the history or resolving conflicts where the whitespaces/indentation creates some confusion. So, I would prefer to avoid the changes from this specific PR, we can create another PR specific to those changes.

**Comment by robertoschwald** [comment]
Done. If you like me to squash commits, feel free to comment.

**Comment by puneetbehl** [comment]
I will squash it directly while merging, thanks!

**Pull request merged**
