### PR TITLE
IntelliJ GroovyDSL extension for migration DSL

### PR DESCRIPTION
**Pull request by snimavat**
I have written a GDSL for intellij idea which would provide the code completion / suggestions for database migration changelog files (groovy) Read this [article](https://confluence.jetbrains.com/display/GRVY/Scripting+IDE+for+DSL+awareness) for more details 

Other frameworks like [spock](https://github.com/spockframework/spock/commit/13bd4202f7d4ed5dc69b3269e8086780085e6236) and [gparse](https://github.com/GPars/GPars/blob/master/src/main/groovy/groovyx/gpars/Definitions.gdsl) also uses this to enhance code completion/suggestions for intellij idea

migration-test-2

It can be further enhanced by the community.

### CODE REVIEW

**Comment by jameskleeh** [comment]
This is fantastic! Can you target the 2.x branch?

**Comment by snimavat** [comment]
sure.

**Comment by snimavat** [comment]
Check #117 @jameskleeh

**Comment by snimavat** [comment]
@jameskleeh 
If you guyz wokr on this script further and make the changes to gdsl script while gdsl is already loaded by intellij, then you may need to delete the file ~/Library/Preferences/<IntellijVersion>/options/dslActivationStatus.xml to have ur changes picked up. Users will never need to do this, because they will never modify the original gdsl which is in classpath

**Comment by jameskleeh** [comment]
Thank you very much for this contribution!

**Pull request closed without merging**
